# SPDX-FileCopyrightText: 2025 Ryan Cao <hello@ryanccn.dev>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "moldau"
version = "0.3.0"
edition = "2024"

description = "Modern version manager for Node.js package managers"
authors = ["Ryan Cao <hello@ryanccn.dev>"]
license = "GPL-3.0-or-later"
homepage = "https://github.com/ryanccn/moldau"
repository = "https://github.com/ryanccn/moldau.git"

[dependencies]
anstream = "1.0.0"
aws-lc-rs = "1.18.1"
base64 = "0.23.1"
clap = { version = "4.6.6", features = ["derive", "string"] }
clap_complete = "4.6.9"
color-eyre = { version = "0.6.5", default-features = false }
env_logger = "0.11.11"
eyre = "0.6.14"
flate2 = "1.1.10"
hex = "0.4.3"
indicatif = { version = "0.18.6", features = ["improved_unicode"] }
log = "0.4.34"
owo-colors = { version = "4.4.0" }
reqwest = { version = "0.13.5", features = ["json", "deflate", "gzip", "brotli", "zstd"] }
semver = { version = "1.0.28", features = ["serde"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = { version = "1.0.151", features = ["preserve_order"] }
tar = "0.4.46"
tempfile = "3.27.0"
tokio = { version = "1.53.1", features = ["full"] }
which = "8.0.6"
zip = "8.6.0"

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
