# SPDX-FileCopyrightText: 2025 Ryan Cao <hello@ryanccn.dev>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Check npm registry keys

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 0 * * 0"

permissions:
  contents: read

jobs:
  check-npm-keys:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6.0.2
        with:
          persist-credentials: false

      - name: Install Nix
        uses: cachix/install-nix-action@616559265b40713947b9c190a8ff4b507b5df49b # ratchet:cachix/install-nix-action@v31.10.4

      - name: Check
        run: ./.github/check-npm-keys.sh
